package com.hiveworkshop.rms.ui.application;

import com.hiveworkshop.rms.ui.icons.RMSIcons;
import com.hiveworkshop.rms.ui.util.LanguageReader;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.InputStream;
import java.text.MessageFormat;
import java.util.List;
import java.util.ResourceBundle;

public class MainFrame extends JFrame {
	public static Image MAIN_PROGRAM_ICON;

	public static MainFrame frame;
	public static MainPanel panel;
	public static JMenuBar menuBar;

	private static final ResourceBundle resourceBundle = LanguageReader.getRb();

	public static MainPanel getPanel() {
		return panel;
	}

	public MainFrame(final String title) {
		super(title);
		MAIN_PROGRAM_ICON = new ImageIcon(RMSIcons.loadProgramImage("retera.jpg")).getImage();

		setBounds(0, 0, 1000, 650);
		panel = new MainPanel();
		setContentPane(panel);
		menuBar = MenuBar.createMenuBar(panel);
		setJMenuBar(menuBar);// MainFrame.class.getResource("ImageBin/DDChicken2.png")
		setIconImage(MAIN_PROGRAM_ICON);

		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(final WindowEvent e) {
				if (MenuBar.closeAll(panel)) {
					System.exit(0);
				}
			}
		});
		setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

		setLocationRelativeTo(null);
		setVisible(true);
	}

	public static void create(final List<String> startupModelPaths) {
		frame = new MainFrame(MessageFormat.format(resourceBundle.getString("retera.model.studio.0"), getVersion()));
		panel.init();
		FileDialog fileDialog = new FileDialog(panel);
		if (!startupModelPaths.isEmpty()) {
			for (final String path : startupModelPaths) {
				fileDialog.openFile(new File(path));
			}
		}
	}

	// Uses version.txt generated by modelstudio/build.gradle to set the title of the main window
	public static String getVersion() {
		String version = resourceBundle.getString("build.version"); // In case the file doesn't exists, and during development
		try (InputStream inputStream = MainFrame.class.getClassLoader().getResourceAsStream("version.txt")) {
			if (inputStream != null) {
				version = new String(inputStream.readAllBytes());
			}
		} catch (Exception exception) {
			exception.printStackTrace();
		}
		return version;
	}
}
